routes/admin.php
<?php

use App\Http\Controllers\Admin\ArticlesController;
use App\Http\Controllers\Admin\CategoriesController;
use App\Http\Controllers\Admin\CustomAuthController;
use App\Http\Controllers\Admin\ReservationsServicesController;
require 'breadcrumbs.php';



Route::get('login',[CustomAuthController::class,'login'])->name('login');
Route::get('signup',[CustomAuthController::class,'signup'])->name('signup');
Route::post('postlogin',[CustomAuthController::class,'postlogin'])->name('postlogin'); 
Route::post('signupsave', [CustomAuthController::class,'signupsave'])->name('signupsave'); 
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath','auth' ]
    ], function(){
       
        Route::resource('categories', CategoriesController::class);
        Route::resource('articles', ArticlesController::class);
        Route::resource('reservations-services', ReservationsServicesController::class);
        Route::controller(CustomAuthController::class)->group(function () {
            Route::get('/','home')->name('home'); 
            Route::get('dashboard','dashboard'); 
            Route::get('signout', 'signOut')->name('signout');
            Route::get('forget-password','showForgetPasswordForm')->name('forget.password.get');
            Route::post('forget-password', 'submitForgetPasswordForm')->name('forget.password.post'); 
            Route::get('reset-password/{token}','showResetPasswordForm')->name('reset.password.get');
            Route::post('reset-password','submitResetPasswordForm')->name('reset.password.post');
        });
        
    });


// Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => ['auth', 'checkLogin']], function () {

//     Route::get('/', function () {
//         return view('dashboard.layouts.layout');
//     })->name('index');


//     Route::get('/settings', [SettingController::class, 'index'])->name('settings');

//     Route::post('/settings/update/{setting}', [SettingController::class, 'update'])->name('settings.update');


//     Route::get('/users/all', [UserController::class, 'getUsersDatatable'])->name('users.all');
//     Route::post('/users/delete', [UserController::class, 'delete'])->name('users.delete');


//     Route::get('/category/all', [CategoryController::class, 'getCategoriesDatatable'])->name('category.all');
//     Route::post('/category/delete', [CategoryController::class, 'delete'])->name('category.delete');



//     Route::get('/posts/all', [PostsController::class, 'getPostsDatatable'])->name('posts.all');
//     Route::post('/posts/delete', [PostsController::class, 'delete'])->name('posts.delete');


//     Route::resources([
//         'users' => UserController::class,
//         'category' => CategoryController::class,
//         'posts' => PostsController::class,
//     ]);
// });

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::get('/', function () {
//     return view('admin.index');
// });

// Route::get('/app', function () {
//     return view('admin.app');
// });


// Route::get('/gest', function () {
//     return view('admin.gest');
// });

// Route::get('/login', function () {
//     return view('admin.auth.login');
// });


// Route::get('/register', function () {
//     return view('admin.auth.register');
// });


// Route::get('/forgot', function () {
//     return view('admin.auth.forgot');
// });


// Route::get('/reset', function () {
//     return view('admin.auth.reset');
// });


// Route::get('/verify', function () {
//     return view('admin.auth.verify');
// }); 

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
require __DIR__ . '/admin.php';

// Route::get('/', [IndexController::class, 'index'])->name('index');
// Route::get('/categories/{category}', [WebsiteCategoryController::class, 'show'])->name('category');
// Route::get('/post/{post}', [PostController::class, 'show'])->name('post');

app/Models/ReservationService.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ReservationService extends Model
{
    use HasFactory;
}

resources/views/admin/ReservationService/create.blade.php
@extends('admin.app')


@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('reservations-services.index') }}">@lang('Reservations Blogs')</a>
</li>
<li class="breadcrumb-item active" ><a href="{{ route('reservations-services.create') }}" >@lang('Add New')</a>
</li>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <form method="POST" action="{{ route('reservations-services.store') }}">
                @csrf
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"> @lang('Add New') @lang('Reservation Blog') </h4>
                    </div>
                    
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="name">@lang('Name')</label>
                                    <input class="form-control" required id="name" type="text"  name="name"autofocus=""
                                    placeholder="@lang('Name')" aria-describedby="name"  tabindex="1" />
                                    @if ($errors->has('name'))
                                    <span class="text-danger">{{ $errors->first('name') }}</span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="email">@lang('Email')</label>
                                    <input class="form-control" required id="email" type="text"  name="email"autofocus=""
                                    placeholder="@lang('Email')" aria-describedby="email"  tabindex="1" />
                                    @if ($errors->has('email'))
                                    <span class="text-danger">{{ $errors->first('email') }}</span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="mobile">@lang('Mobile')</label>
                                    <input class="form-control" required id="mobile" type="text"  name="mobile"autofocus=""
                                    placeholder="@lang('Mobile')" aria-describedby="mobile"  tabindex="1" />
                                    @if ($errors->has('mobile'))
                                    <span class="text-danger">{{ $errors->first('mobile') }}</span>
                                    @endif
                                </div>
                            </div>

                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="Detail">@lang('Detail')</label>
                                    <textarea  class="form-control" id="detail" name="detail"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-primary waves-effect waves-float waves-light" type="submit">@lang('Submit')</button>
                    </div>
                </div>
    
            </form>
        </div>
    </div>
@endsection

resources/views/admin/ReservationService/edit.blade.php
@extends('admin.app')


@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('reservations-services.index') }}">@lang('Reservations Blogs')</a>
</li>
<li class="breadcrumb-item active" ><a href="{{ route('reservations-services.create') }}" >@lang('Modify')</a>
</li>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <form method="POST" action="{{ route('reservations-services.update', $ReservationService->id) }}">
                @csrf
                @method('PUT') 
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"> @lang('Modify') @lang('Reservation Blog') </h4>
                    </div>
                    
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="name">@lang('Name')</label>
                                    <input class="form-control" id="name" type="text"  name="name"autofocus=""
                                    placeholder="@lang('Name')" aria-describedby="name"  tabindex="1"  value="{{ $ReservationService->name }}"/>
                                    @if ($errors->has('name'))
                                    <span class="text-danger">{{ $errors->first('name') }}</span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="email">@lang('Email')</label>
                                    <input class="form-control" id="email" type="text"  name="email"autofocus=""
                                    placeholder="@lang('Email')" aria-describedby="email"  value="{{ $ReservationService->email }}" tabindex="1" />
                                    @if ($errors->has('email'))
                                    <span class="text-danger">{{ $errors->first('email') }}</span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="mobile">@lang('Mobile')</label>
                                    <input class="form-control" id="mobile" type="text"  name="mobile"autofocus=""
                                    placeholder="@lang('Mobile')" aria-describedby="mobile" value="{{ $ReservationService->mobile }}"  tabindex="1" />
                                    @if ($errors->has('mobile'))
                                    <span class="text-danger">{{ $errors->first('mobile') }}</span>
                                    @endif
                                </div>
                            </div>
        
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="detail">@lang('Detail')</label>
                                    <textarea  class="form-control" id="detail" name="detail">{{ $ReservationService->detail }}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                  
                    <div class="card-footer">
                        <button class="btn btn-primary waves-effect waves-float waves-light" type="submit">@lang('Modify')</button>
                    </div>
                </div>
    
            </form>
        </div>
    </div>
@endsection

resources/views/admin/ReservationService/index.blade.php
@extends('admin.app')

@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('reservations-services.index') }}">@lang('Reservations Blogs')</a>
</li>

@endsection

@section('content')
    <div class="row" id="basic-table">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">@lang('Reservations Blogs')</h4>
                    <div class="heading-elements">
                        <ul class="list-inline mb-0">
                            <li>
                                <a href="{{ route('reservations-services.create') }}"
                                   class="btn btn-icon btn-primary waves-effect"
                                   data-bs-toggle="tooltip"
                                   data-bs-placement="left"
                                   title="@lang('Add New')">
                                    <i data-feather='plus-square'></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>@lang('Name')</th>
                            <th>@lang('Email')</th>
                            <th>@lang('Mobile')</th>
                            <th class="width-150"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($AllData as $Data)
                            <tr>
                                <td>
                                    <span class="fw-bold">{{$Data->name}}</span>
                                </td>
                                <td>
                                    <span class="fw-bold">{{$Data->email}}</span>
                                </td>
                                <td>
                                    <span class="fw-bold">{{$Data->mobile}}</span>
                                </td>
                               
                                <td>

                                    <a href="{{route('reservations-services.show',$Data)}}" class="btn btn-icon btn-outline-primary waves-effect">
                                        <i data-feather='eye'></i>
                                    </a>


                                    <a href="{{route('reservations-services.edit',$Data)}}" class="btn btn-icon btn-outline-primary waves-effect">
                                        <i data-feather='edit'></i>
                                    </a>
                                

                                    {{ html()->form('DELETE', route('reservations-services.destroy',$Data))->class('d-inline')->open()}}
                                    <button type="submit" class="btn btn-icon btn-outline-danger waves-effect confirm">
                                        <i data-feather='trash-2'></i>
                                    </button>
                                    {{ html()->form()->close()}}
                                </td> 
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5" class="text-center"></td>
                            </tr>
                        @endforelse
                        
                        </tbody>
                       
                    </table>
                    <div class="justify-content-center">
                        {!! $AllData->links('pagination::bootstrap-4') !!}

            
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/ReservationService/show.blade.php
@extends('admin.app')
@section('content')
    <div class="row">
        <div class="col-md-12">
     
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"> @lang('View') @lang('Reservation Blog') </h4>
                    </div>
                    
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="name">@lang('Name') </label>
                                    <p>{{  $ReservationService->name }}</p>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="email">@lang('Email') </label>
                                    <p>{{  $ReservationService->email }}</p>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="mobile">@lang('Mobile') </label>
                                    <p>{{  $ReservationService->mobile }}</p>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="detail">@lang('Detail') </label>
                                    <p>{{  $ReservationService->detail }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
    
        </div>
    </div>
@endsection