routes/admin.php
<?php

use App\Http\Controllers\Admin\ArticlesController;
use App\Http\Controllers\Admin\CategoriesController;
use App\Http\Controllers\Admin\CustomAuthController;
use App\Http\Controllers\Admin\ReservationsServicesController;
require 'breadcrumbs.php';



Route::get('login',[CustomAuthController::class,'login'])->name('login');
Route::get('signup',[CustomAuthController::class,'signup'])->name('signup');
Route::post('postlogin',[CustomAuthController::class,'postlogin'])->name('postlogin'); 
Route::post('signupsave', [CustomAuthController::class,'signupsave'])->name('signupsave'); 
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath','auth' ]
    ], function(){
       
        Route::resource('categories', CategoriesController::class);
        Route::resource('articles', ArticlesController::class);
        Route::resource('reservations-services', ReservationsServicesController::class);
        Route::controller(CustomAuthController::class)->group(function () {
            Route::get('/','home')->name('home'); 
            Route::get('dashboard','dashboard'); 
            Route::get('signout', 'signOut')->name('signout');
            Route::get('forget-password','showForgetPasswordForm')->name('forget.password.get');
            Route::post('forget-password', 'submitForgetPasswordForm')->name('forget.password.post'); 
            Route::get('reset-password/{token}','showResetPasswordForm')->name('reset.password.get');
            Route::post('reset-password','submitResetPasswordForm')->name('reset.password.post');
        });
        
    });


// Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => ['auth', 'checkLogin']], function () {

//     Route::get('/', function () {
//         return view('dashboard.layouts.layout');
//     })->name('index');


//     Route::get('/settings', [SettingController::class, 'index'])->name('settings');

//     Route::post('/settings/update/{setting}', [SettingController::class, 'update'])->name('settings.update');


//     Route::get('/users/all', [UserController::class, 'getUsersDatatable'])->name('users.all');
//     Route::post('/users/delete', [UserController::class, 'delete'])->name('users.delete');


//     Route::get('/category/all', [CategoryController::class, 'getCategoriesDatatable'])->name('category.all');
//     Route::post('/category/delete', [CategoryController::class, 'delete'])->name('category.delete');



//     Route::get('/posts/all', [PostsController::class, 'getPostsDatatable'])->name('posts.all');
//     Route::post('/posts/delete', [PostsController::class, 'delete'])->name('posts.delete');


//     Route::resources([
//         'users' => UserController::class,
//         'category' => CategoryController::class,
//         'posts' => PostsController::class,
//     ]);
// });

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::get('/', function () {
//     return view('admin.index');
// });

// Route::get('/app', function () {
//     return view('admin.app');
// });


// Route::get('/gest', function () {
//     return view('admin.gest');
// });

// Route::get('/login', function () {
//     return view('admin.auth.login');
// });


// Route::get('/register', function () {
//     return view('admin.auth.register');
// });


// Route::get('/forgot', function () {
//     return view('admin.auth.forgot');
// });


// Route::get('/reset', function () {
//     return view('admin.auth.reset');
// });


// Route::get('/verify', function () {
//     return view('admin.auth.verify');
// }); 

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
require __DIR__ . '/admin.php';

// Route::get('/', [IndexController::class, 'index'])->name('index');
// Route::get('/categories/{category}', [WebsiteCategoryController::class, 'show'])->name('category');
// Route::get('/post/{post}', [PostController::class, 'show'])->name('post');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Staudenmeir\EloquentEagerLimit\HasEagerLimit;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;

class Article extends Model implements TranslatableContract
{
    use HasFactory , Translatable , SoftDeletes , HasEagerLimit;
    public $translatedAttributes = ['title', 'content'];
    protected $fillable = ['id', 'image', 'category_id', 'created_at', 'updated_at'];

    public function category()
    {
       return $this->belongsTo(Category::class , 'category_id');
    }
}

app/Http/Controllers/Admin/ArticlesController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Models\Article;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ArticlesController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $Articles = Article::all();
        return view('admin.articles.index', compact('Articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $categories = Category::all();
        return view('admin.articles.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $data = Article::create($request->all());     
        if($request->file('image')){
            $file= $request->file('image');
            $filename= date('YmdHi'). $file->getClientOriginalName();
            $file-> move(public_path('public/Image'), $filename);
            $data['image']= $filename;
        }

        $data['article_date'] = $request->article_date;
        $data->save();   
        return redirect('articles');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $Article = Article::find($id);
        return view('admin.Article.show', compact('Article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $categories = Category::all();
        $Article = Article::find($id);
        return view('admin.articles.edit', compact('categories','Article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $Article = Article::find($id);
        if($request->file('image')){
            $file= $request->file('image');
            $filename= date('YmdHi'). $file->getClientOriginalName();
            $file-> move(public_path('public/Image'), $filename);
            $Article['image']= $filename;
        }

        $Article['article_date'] = $request->article_date;
        $Article->update($request->all());
        return redirect('articles');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Article = Article::find($id);
        $Article->delete();

        // redirect
        return redirect('articles');
    }
}

resources/views/admin/articles/create.blade.php
@extends('admin.app')

@section('css')
   <!-- BEGIN: Page CSS-->
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/vendors/css/vendors.min.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/vendors/css/pickers/pickadate/pickadate.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/vendors/css/pickers/flatpickr/flatpickr.min.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/css/core/menu/menu-types/vertical-menu.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/css/plugins/forms/pickers/form-flat-pickr.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/css/plugins/forms/pickers/form-pickadate.css">
  <!-- END: Page CSS-->
@endsection

@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('articles.index') }}">@lang('articles')</a>
</li>
<li class="breadcrumb-item active" ><a href="{{ route('articles.create') }}" >@lang('Add New')</a>
</li>
@endsection

@section('content')
<section id="basic-tabs-components">
    <div class="row match-height">
        <!-- Basic Tabs starts -->
        <div class="col-lg-12">
            <form method="POST" action="{{ route('articles.store') }}" enctype="multipart/form-data">
            @csrf


            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"> @lang('Add New') @lang('Article') </h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Categories')</label>
                                <select class="select-search form-control" required data-style="btn-default btn-lg" data-width="100%"
                                name="category_id" data-placeholder="">
                                @foreach ($categories as $category)
                                <option value="{{  $category->id }}">{{  $category->title }}</option>
                                @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label for="customFile1" class="form-label">@lang('Image')  </label>
                                <input class="form-control" type="file" required name="image" id="customFile1" required />
                            </div>
                        </div>
                   

                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Date')</label>
                                <input type="text" id="fp-default" name="article_date" required 
                                class="form-control flatpickr-basic"
                                placeholder="YYYY-MM-DD" />
                            </div>
                        </div>
                    </div>
                    <ul class="nav nav-tabs" role="tablist">
                        @foreach (config('app.languages') as $key => $lang)
                        <li class="nav-item">
                            <a class="nav-link @if ($loop->index == 0) active @endif" 
                                id="{{ $lang }}-tab" data-bs-toggle="tab" href="#{{ $key }}" 
                                aria-controls="{{ $lang }}" role="tab" aria-selected="true">{{ $lang }}</a>
                        </li>
                        @endforeach
                    </ul>
                    <div class="tab-content">
                        @foreach (config('app.languages') as $key => $lang)
                        <div class="tab-pane @if ($loop->index == 0) active @endif" id="{{ $key }}" 
                        aria-labelledby="{{ $key }}-tab" role="tabpanel">
                        <div class="row">
                            <div class="col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="TitleInput">@lang('Title')</label>
                                    <input id="TitleInput" required   name="{{$key}}[title]" class="form-control form-control-lg"
                                     type="text" placeholder="@lang('Title') {{$key}}" />
                                     
                                </div>
                                @error($key.'title') 
                                {{  $message }}
                                @enderror
                            </div>
                            <div class="col-12">
                                <div class="mb-1">
                                    <label class="form-label" required for="exampleFormControlTextarea1">@lang('Content')</label>
                                    <textarea class="form-control" name="{{$key}}[content]" id="exampleFormControlTextarea1" rows="3" 
                                    placeholder="@lang('Content')"></textarea>
                                </div>
                                @error($key.'content') 
                                {{  $content }}
                                @enderror
                            </div>
                        </div>
                            
                        </div>
                        @endforeach
                    </div>
                
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary waves-effect waves-float waves-light" type="submit">@lang('Submit')</button>
                </div>
            </div>
           </form>
        </div>
        <!-- Basic Tabs ends -->

    </div>
</section>
@endsection

@section('js')
<!-- BEGIN: Theme JS-->
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/pickadate/picker.js"></script>
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/pickadate/picker.date.js"></script>
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/pickadate/picker.time.js"></script>
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/pickadate/legacy.js"></script>
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/flatpickr/flatpickr.min.js"></script>
<script src="{{asset('admin')}}/app-assets/js/scripts/components/components-navs.js"></script>
<script src="{{asset('admin')}}/app-assets/js/scripts/forms/pickers/form-pickers.js"></script>
<!-- END: Theme JS-->
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.app')

@section('css')
   <!-- BEGIN: Page CSS-->
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/vendors/css/vendors.min.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/vendors/css/pickers/pickadate/pickadate.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/vendors/css/pickers/flatpickr/flatpickr.min.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/css/core/menu/menu-types/vertical-menu.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/css/plugins/forms/pickers/form-flat-pickr.css">
   <link rel="stylesheet" type="text/css" href="{{asset('admin')}}/app-assets/css/plugins/forms/pickers/form-pickadate.css">
  <!-- END: Page CSS-->
@endsection


@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('articles.index') }}">@lang('articles')</a>
</li>
<li class="breadcrumb-item active" ><a href="{{ route('articles.edit', $Article->id)}}" >@lang('Modify')</a>
</li>
@endsection
@section('content')

<section id="basic-tabs-components">
    <div class="row match-height">
        <!-- Basic Tabs starts -->
        <div class="col-lg-12">
            <form method="POST" action="{{ route('articles.update', $Article->id) }}"
                 enctype="multipart/form-data">
                 @csrf  

                 @method('PUT')


            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"> @lang('Modify') @lang('Articles') </h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Categories')</label>
                                <select class="select-search form-control" required data-style="btn-default btn-lg" data-width="100%"
                                name="category_id" data-placeholder="">
                                @foreach ($categories as $category)
                                <option value="{{  $category->id }}" @if ($category->id == $Article->category_id)
                                    selected @endif>{{  $category->title }} </option>
                                @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label for="customFile1" class="form-label">@lang('Image')  </label>
                                <input class="form-control" type="file"  name="image" id="customFile1" required />
                            </div>
                        </div>
                   

                        <div class="col-md-6 col-12">
                            <div class="mb-1">
                                <label class="form-label" for="fp-default">@lang('Date')</label>
                                <input type="text" id="fp-default" name="article_date" required 
                                class="form-control flatpickr-basic"
                                placeholder="YYYY-MM-DD"  value="{{ $Article->article_date }}"/>
                            </div>
                        </div>
                    </div>
                    <ul class="nav nav-tabs" role="tablist">
                        @foreach (config('app.languages') as $key => $lang)
                        <li class="nav-item">
                            <a class="nav-link @if ($loop->index == 0) active @endif" 
                                id="{{ $lang }}-tab" data-bs-toggle="tab" href="#{{ $key }}" 
                                aria-controls="{{ $lang }}" role="tab" aria-selected="true">{{ $lang }}</a>
                        </li>
                        @endforeach
                    </ul>
                    <div class="tab-content">
                        @foreach (config('app.languages') as $key => $lang)
                        <div class="tab-pane @if ($loop->index == 0) active @endif" id="{{ $key }}" 
                        aria-labelledby="{{ $key }}-tab" role="tabpanel">
                        <div class="row">
                            <div class="col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="TitleInput">@lang('Title')</label>
                                    <input id="TitleInput" required   name="{{$key}}[title]" class="form-control form-control-lg"
                                     type="text" placeholder="@lang('Title') {{$key}}" value={{ $Article->translate($key)->title ?? '' }}  />
                                     
                                </div>
                                @error($key.'title') 
                                {{  $message }}
                                @enderror
                            </div>
                            <div class="col-12">
                                <div class="mb-1">
                                    <label class="form-label" required for="exampleFormControlTextarea1">وصف</label>
                                    <textarea class="form-control"   name="{{$key}}[content]" id="exampleFormControlTextarea1" rows="3" placeholder="Textarea">{{ $Article->translate($key)->content ?? '' }}</textarea>
                                </div>
                                @error($key.'content') 
                                {{  $content }}
                                @enderror
                            </div>
                        </div>
                            
                        </div>
                        @endforeach
                    </div>
                
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary waves-effect waves-float waves-light" type="submit">@lang('Modify')</button>
                </div>
            </div>
           </form>
        </div>
        <!-- Basic Tabs ends -->

    </div>
</section>
@endsection

@section('js')
<!-- BEGIN: Theme JS-->
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/pickadate/picker.js"></script>
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/pickadate/picker.date.js"></script>
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/pickadate/picker.time.js"></script>
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/pickadate/legacy.js"></script>
<script src="{{asset('admin')}}/app-assets/vendors/js/pickers/flatpickr/flatpickr.min.js"></script>
<script src="{{asset('admin')}}/app-assets/js/scripts/components/components-navs.js"></script>
<script src="{{asset('admin')}}/app-assets/js/scripts/forms/pickers/form-pickers.js"></script>
<!-- END: Theme JS-->
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.app')

@section('css')
   <!-- BEGIN: Page CSS-->
  <!-- END: Page CSS-->
@endsection


@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item active"><a href="{{ route('articles.index') }}">@lang('articles')</a>
</li>
@endsection


@section('content')
<div class="row" id="basic-table">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">@lang('Articles')</h4>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li>
                            <a href="{{route('articles.create')}}"
                               class="btn btn-icon btn-primary waves-effect"
                               data-bs-toggle="tooltip"
                               data-bs-placement="left"
                               title="@lang('Add New')">
                                <i data-feather='plus-square'></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>@lang('Article')</th>
                        <th>@lang('Category')</th>
                        <th class="width-150"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($Articles as $article)
                        <tr>
                            <td>
                                <span class="fw-bold">{{$article->title}}</span>
                            </td>
                            <td>
                                <span class="fw-bold">{{$article->category->title ?? ''}}</span>
                            </td>
                           
                            <td>

                                {{-- <a href="{{route('articles.show',$article)}}" class="btn btn-icon btn-outline-primary waves-effect">
                                    <i data-feather='eye'></i>
                                </a> --}}


                                <a href="{{route('articles.edit',$article)}}" class="btn btn-icon btn-outline-primary waves-effect">
                                    <i data-feather='edit'></i>
                                </a>
                            

                                {{ html()->form('DELETE',route('articles.destroy',$article))->class('d-inline')->open()}}
                                <button type="submit" class="btn btn-icon btn-outline-danger waves-effect confirm">
                                    <i data-feather='trash-2'></i>
                                </button>
                                {{ html()->form()->close()}}
                            </td> 
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="text-center"></td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<!-- BEGIN: Theme JS-->
<script src="{{asset('admin')}}/app-assets/js/scripts/components/components-navs.js"></script>
<!-- END: Theme JS-->
@endsection

resources/views/admin/articles/show.blade.php
@extends('admin.app')
@section('content')
    <div class="row">
        <div class="col-md-12">
     
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"> @lang('View') @lang('Reservation Blog') </h4>
                    </div>
                    
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="name">@lang('View') </label>
                                    <p>{{  $ReservationService->name }}</p>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="email">@lang('Email') </label>
                                    <p>{{  $ReservationService->email }}</p>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="mobile">@lang('Mobile') </label>
                                    <p>{{  $ReservationService->mobile }}</p>
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="detail">@lang('Detail') </label>
                                    <p>{{  $ReservationService->detail }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
    
        </div>
    </div>
@endsection