routes/admin.php
<?php

use App\Http\Controllers\Admin\ArticlesController;
use App\Http\Controllers\Admin\CategoriesController;
use App\Http\Controllers\Admin\CustomAuthController;
use App\Http\Controllers\Admin\ReservationsServicesController;
require 'breadcrumbs.php';



Route::get('login',[CustomAuthController::class,'login'])->name('login');
Route::get('signup',[CustomAuthController::class,'signup'])->name('signup');
Route::post('postlogin',[CustomAuthController::class,'postlogin'])->name('postlogin'); 
Route::post('signupsave', [CustomAuthController::class,'signupsave'])->name('signupsave'); 
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath','auth' ]
    ], function(){
       
        Route::resource('categories', CategoriesController::class);
        Route::resource('articles', ArticlesController::class);
        Route::resource('reservations-services', ReservationsServicesController::class);
        Route::controller(CustomAuthController::class)->group(function () {
            Route::get('/','home')->name('home'); 
            Route::get('dashboard','dashboard'); 
            Route::get('signout', 'signOut')->name('signout');
            Route::get('forget-password','showForgetPasswordForm')->name('forget.password.get');
            Route::post('forget-password', 'submitForgetPasswordForm')->name('forget.password.post'); 
            Route::get('reset-password/{token}','showResetPasswordForm')->name('reset.password.get');
            Route::post('reset-password','submitResetPasswordForm')->name('reset.password.post');
        });
        
    });


// Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => ['auth', 'checkLogin']], function () {

//     Route::get('/', function () {
//         return view('dashboard.layouts.layout');
//     })->name('index');


//     Route::get('/settings', [SettingController::class, 'index'])->name('settings');

//     Route::post('/settings/update/{setting}', [SettingController::class, 'update'])->name('settings.update');


//     Route::get('/users/all', [UserController::class, 'getUsersDatatable'])->name('users.all');
//     Route::post('/users/delete', [UserController::class, 'delete'])->name('users.delete');


//     Route::get('/category/all', [CategoryController::class, 'getCategoriesDatatable'])->name('category.all');
//     Route::post('/category/delete', [CategoryController::class, 'delete'])->name('category.delete');



//     Route::get('/posts/all', [PostsController::class, 'getPostsDatatable'])->name('posts.all');
//     Route::post('/posts/delete', [PostsController::class, 'delete'])->name('posts.delete');


//     Route::resources([
//         'users' => UserController::class,
//         'category' => CategoryController::class,
//         'posts' => PostsController::class,
//     ]);
// });

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::get('/', function () {
//     return view('admin.index');
// });

// Route::get('/app', function () {
//     return view('admin.app');
// });


// Route::get('/gest', function () {
//     return view('admin.gest');
// });

// Route::get('/login', function () {
//     return view('admin.auth.login');
// });


// Route::get('/register', function () {
//     return view('admin.auth.register');
// });


// Route::get('/forgot', function () {
//     return view('admin.auth.forgot');
// });


// Route::get('/reset', function () {
//     return view('admin.auth.reset');
// });


// Route::get('/verify', function () {
//     return view('admin.auth.verify');
// }); 

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
require __DIR__ . '/admin.php';

// Route::get('/', [IndexController::class, 'index'])->name('index');
// Route::get('/categories/{category}', [WebsiteCategoryController::class, 'show'])->name('category');
// Route::get('/post/{post}', [PostController::class, 'show'])->name('post');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Staudenmeir\EloquentEagerLimit\HasEagerLimit;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;

class Category extends Model implements  TranslatableContract
{
    use \Staudenmeir\EloquentEagerLimit\HasEagerLimit;

    use Translatable , HasEagerLimit , HasFactory , SoftDeletes;


    public $translatedAttributes = ['title', 'content'];
    protected $fillable = [ 'id', 'created_at', 'updated_at','deleted_at'];

    public function posts()
    {
       return $this->hasMany(Post::class);
    }

}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Refregion;


class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // get all the Category
        $categories = Category::all();
        return view('admin.categories.index', compact('categories'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        
        //
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    //    foreach(config('app.languages') as $key => $val){
    //         $request->validate([
    //             $key.'title'=>'required'
    //         ]);
    //    }
        

        Category::create($request->all());        
        return redirect('categories');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $Category = Category::find($id);
        return view('admin.categories.show', compact('Category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Category = Category::find($id);


        return view('admin.categories.edit', compact('Category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       



        $Category = Category::find($id);
        $Category->update($request->all());
        return redirect('categories');
       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Category = Category::find($id);
        $Category->delete();

        // redirect
        return redirect('categories');
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.app')

@section('css')
   <!-- BEGIN: Page CSS-->
  <!-- END: Page CSS-->
@endsection


@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('categories.index') }}">@lang('Categories')</a>
</li>
<li class="breadcrumb-item active" ><a href="{{ route('categories.create') }}" >@lang('Add New')</a>
</li>
@endsection


@section('content')
<section id="basic-tabs-components">
    <div class="row match-height">
        <!-- Basic Tabs starts -->
        <div class="col-lg-12">
            <form method="POST" action="{{ route('categories.store') }}">
            @csrf
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"> @lang('Add New') @lang('Category') </h4>
                </div>
                <div class="card-body">
                    <ul class="nav nav-tabs" role="tablist">
                        @foreach (config('app.languages') as $key => $lang)
                        <li class="nav-item">
                            <a class="nav-link @if ($loop->index == 0) active @endif" 
                                id="{{ $lang }}-tab" data-bs-toggle="tab" href="#{{ $key }}" 
                                aria-controls="{{ $lang }}" role="tab" aria-selected="true">{{ $lang }}</a>
                        </li>
                        @endforeach
                    </ul>
                    <div class="tab-content">
                        @foreach (config('app.languages') as $key => $lang)
                        <div class="tab-pane @if ($loop->index == 0) active @endif" id="{{ $key }}" 
                        aria-labelledby="{{ $key }}-tab" role="tabpanel">
                        <div class="row">
                            <div class="col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="TitleInput">@lang('Title')</label>
                                    <input id="TitleInput"   name="{{$key}}[title]" class="form-control form-control-lg"
                                     type="text" placeholder="@lang('Title') {{$key}}" />
                                     
                                </div>
                                @error($key.'title') 
                                {{  $message }}
                                @enderror
                            </div>
                        </div>
                            
                        </div>
                        @endforeach
                    </div>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary waves-effect waves-float waves-light" type="submit">@lang('Submit')</button>
                </div>
            </div>
           </form>
        </div>
        <!-- Basic Tabs ends -->

    </div>
</section>
@endsection

@section('js')
<!-- BEGIN: Theme JS-->
<script src="{{asset('admin')}}/app-assets/js/scripts/components/components-navs.js"></script>
<!-- END: Theme JS-->
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.app')

@section('css')
   <!-- BEGIN: Page CSS-->
  <!-- END: Page CSS-->
@endsection

@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('categories.index') }}">@lang('Categories')</a>
</li>
<li class="breadcrumb-item active" ><a href="{{ route('categories.create') }}" >@lang('Modify')</a>
</li>
@endsection

@section('content')
<section id="basic-tabs-components">
    <div class="row match-height">
        <!-- Basic Tabs starts -->
        <div class="col-lg-12">
            <form method="POST" action="{{ route('categories.update', $Category->id) }}">
            @csrf
            @method('PUT')
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title"> @lang('Modify') @lang('Category') </h4>
                </div>
                <div class="card-body">
                    <ul class="nav nav-tabs" role="tablist">
                        @foreach (config('app.languages') as $key => $lang)
                        <li class="nav-item">
                            <a class="nav-link @if ($loop->index == 0) active @endif" 
                                id="{{ $lang }}-tab" data-bs-toggle="tab" href="#{{ $key }}" 
                                aria-controls="{{ $lang }}" role="tab" aria-selected="true">{{ $lang }}</a>
                        </li>
                        @endforeach
                    </ul>
                    <div class="tab-content">
                        @foreach (config('app.languages') as $key => $lang)
                        <div class="tab-pane @if ($loop->index == 0) active @endif" id="{{ $key }}" 
                        aria-labelledby="{{ $key }}-tab" role="tabpanel">
                        <div class="row">
                            <div class="col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="TitleInput">@lang('Title')</label>
                                    <input id="TitleInput"  
                                    value={{ $Category->translate($key)->title ?? '' }} name="{{$key}}[title]" class="form-control form-control-lg"
                                     type="text" placeholder="@lang('Title') {{$key}}" />
                                </div>
                            </div>
                        </div>
                            
                        </div>
                        @endforeach
                    </div>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary waves-effect waves-float waves-light" type="submit">@lang('Modify')</button>
                </div>
            </div>
           </form>
        </div>
        <!-- Basic Tabs ends -->

    </div>
</section>
@endsection

@section('js')
<!-- BEGIN: Theme JS-->
<script src="{{asset('admin')}}/app-assets/js/scripts/components/components-navs.js"></script>
<!-- END: Theme JS-->
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.app')

@section('css')
   <!-- BEGIN: Page CSS-->
  <!-- END: Page CSS-->
@endsection


@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('home') }}">@lang('Home')</a>
</li>
<li class="breadcrumb-item"><a href="{{ route('categories.index') }}">@lang('Categories')</a>
</li>
@endsection

@section('content')
<div class="row" id="basic-table">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">@lang('Categories')</h4>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li>
                            <a href="{{route('categories.create')}}"
                               class="btn btn-icon btn-primary waves-effect"
                               data-bs-toggle="tooltip"
                               data-bs-placement="left"
                               title="@lang('Add New')">
                                <i data-feather='plus-square'></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>@lang('Name')</th>
                        <th class="width-150"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($categories as $category)
                        <tr>
                            <td>
                                <span class="fw-bold">{{$category->title}}</span>
                            </td>
                           
                            <td>

                                {{-- <a href="{{route('categories.show',$category)}}" class="btn btn-icon btn-outline-primary waves-effect">
                                    <i data-feather='eye'></i>
                                </a>  --}}


                                <a href="{{route('categories.edit',$category)}}" class="btn btn-icon btn-outline-primary waves-effect">
                                    <i data-feather='edit'></i>
                                </a>
                            

                                {{ html()->form('DELETE',route('categories.destroy',$category))->class('d-inline')->open()}}
                                <button type="submit" class="btn btn-icon btn-outline-danger waves-effect confirm">
                                    <i data-feather='trash-2'></i>
                                </button>
                                {{ html()->form()->close()}}
                            </td> 
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="text-center"></td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<!-- BEGIN: Theme JS-->
<script src="{{asset('admin')}}/app-assets/js/scripts/components/components-navs.js"></script>
<!-- END: Theme JS-->
@endsection

resources/views/admin/categories/show.blade.php
@extends('admin.app')
@section('content')
    <div class="row">
        <div class="col-md-12">
     
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"> @lang('View') @lang('Category') </h4>
                    </div>
                    
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="mb-1">
                                    <label class="form-label" for="name">@lang('Name') </label>
                                    <p>{{ $Category->translate($key)->title ?? '' }} </p>
                                </div>
                            </div>
                           
                        </div>
                    </div>
                    
                </div>
    
        </div>
    </div>
@endsection